### PR TITLE
Fixed Namespaces, HexView, Disassembly view, and keypress events

### PR DESCRIPTION
**Pull request by neoh4x0r**
This PR mainly fixes:

1. Traceback crashes due to attributes not being in the global Qt namespace (eg. enum values need to be prefixed with the name of the enum, Qt.NAME.MEMBER)
2. The Hex and ASCII view now correctly shows all 16 bytes (instead of 8) and  unprintable characters are replaced with periods.
3. Scrolling via scrollbars and page up/down now works -- Eg. The scroll event will now only happen once (as opposed to getting stuck and scrolling indefinitely).
4. Keypress events (QKeyCombinations) now work properly and the dictionary can now return the methods to execute.

NOTE: This is also an update to PR #142

I will have more to add at a later time -- which is why I created this as a draft.

### CODE REVIEW

**Comment by N00byKing** [comment]
Looks like i missed a few things! Can you change the branch to merge against to the `pyqt6` branch? You're currently pointing it to `master`

**Comment by neoh4x0r** [comment]
> Looks like i missed a few things! Can you change the branch to merge against to the `pyqt6` branch? You're currently pointing it to `master`

Alright, I just changed it to point the pyqt6 branch.

**Comment by korcankaraokcu** [comment]
It's been a while since the last commit so I assume that the PR chain is done for now. I've decided to check it out and here are my observations:

- Apparently, pyqt6 can be installed via pip. For Kubuntu, using the installer gave me the `Unable to locate package python3-pyqt6` error. Moving pyqt6 dependency to PIP from PKG_MGR in the script will do the trick
- After attaching to a process, process selection screen doesn't close itself, have to do it manually
- Cannot continue after stopping the process due to `TypeError: MainForm.continue_hotkey_pressed() missing 1 required positional argument: 'self'`

Sorry about being late, I think I'll have time for the next 1 or 2 weeks, can help with the testing

**Comment by N00byKing** [comment]
Are you not on the latest release? Ubuntu provides `python3-pyqt6` since release 22.10, and Kubuntu seems to have updated as well.
As for the rest of the issues i'll check them out when i have time, which sadly won't be anytime soon

**Comment by neoh4x0r** [comment]
> * Apparently, pyqt6 can be installed via pip. For Kubuntu, using the installer gave me the `Unable to locate package python3-pyqt6` error. Moving pyqt6 dependency to PIP from PKG_MGR in the script will do the trick

I had to install via pip as well....It looks like python3-pyqt6 will be shipped in Debian Bookworm.

Moving forward I think it would be best to use pip to install -- rather than relying on distros to ship the package (or shipping updated point releases).

> * After attaching to a process, process selection screen doesn't close itself, have to do it manually

I just opended the dialog, selected a process, and clicked open -- the dialog closed itself.

> * Cannot continue after stopping the process due to `TypeError: MainForm.continue_hotkey_pressed() missing 1 required positional argument: 'self'`

The first argument is a pointer to the mainform (self); however, in testing I found that sometimes a boolean value is added as a second argument, in other situations, and it throws an out of range error since the function only takes a pointer to self -- I cannot remember what I was doing to get this second issue (but it wasn't the F1/F1/F3 hotkeys, it was something else).

The wrapped functions are called via SysUtils.py::ignore_exceptions::wrapper(*args,**kwargs) -- to correct the issue I had  stripped the last argument, since it looks like most of these function only took a single argument; however, it didn't check if there was only one argument.

**The hotkey f1/f2/f3 should work now**....I just pushed an update to restore the original behavior of the function and removed the code I added in the wapper to try to fix the issue. Probably better just to let it throw an exception, rather than trying to fix-up the arguments before calling the wrapper functions.

**Comment by korcankaraokcu** [comment]
> Moving forward I think it would be best to use pip to install

Yeah, much healthier dependency wise

> I just opended the dialog, selected a process, and clicked open -- the dialog closed itself

After checking the log, I've noticed that it throws an exception upon clicking the button
```
Traceback (most recent call last):
  File "/home/korcan/PINCE_test/PINCE.py", line 1587, in pushButton_Open_clicked
    if self.parent().attach_to_pid(pid):
  File "/home/korcan/PINCE_test/PINCE.py", line 1232, in attach_to_pid
    self.memory_view_window.on_process_stop()
  File "/home/korcan/PINCE_test/PINCE.py", line 3140, in on_process_stop
    self.refresh_hex_view()
  File "/home/korcan/PINCE_test/PINCE.py", line 2949, in refresh_hex_view
    self.tableView_HexView_Hex.resize_to_contents()
  File "/home/korcan/PINCE_test/GUI/CustomTableViews/HexView.py", line 43, in resize_to_contents
    self.setMinimumWidth(size*1.875)
TypeError: setMinimumWidth(self, int): argument 1 has unexpected type 'float'
```
So yeah, casting the param to int will probably solve the issue. The weird thing is that despite having the same code, you are not getting the exception. You might have uncommitted local changes, please double check for it

Aight, I'm continuing with the remaining issues:
- Break and Trace Instructions feature isn't working. Upon starting the tracing process, it gives this exception:
```
Traceback (most recent call last):
  File "/home/korcan/PINCE_test/PINCE.py", line 3624, in tableWidget_Disassemble_context_menu_event
    actions[action]()
  File "/home/korcan/PINCE_test/PINCE.py", line 3657, in exec_trace_instructions_dialog
    trace_instructions_window = TraceInstructionsWindowForm(current_address, parent=self)
  File "/home/korcan/PINCE_test/PINCE.py", line 4509, in __init__
    self.wait_dialog = TraceInstructionsWaitWidgetForm(address, breakpoint, self)
  File "/home/korcan/PINCE_test/PINCE.py", line 4435, in __init__
    self.setWindowFlags(self.windowFlags() | Qt.Window | Qt.FramelessWindowHint)
AttributeError: type object 'Qt' has no attribute 'Window'
```
- Upon clicking search button in functions window will throw an exception:
```
Traceback (most recent call last):
  File "/home/korcan/PINCE_test/PINCE.py", line 4626, in refresh_table
    self.loading_dialog = LoadingDialogForm(self)
  File "/home/korcan/PINCE_test/PINCE.py", line 1913, in __init__
    self.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint)
AttributeError: type object 'Qt' has no attribute 'FramelessWindowHint'
```
- In libpince reference window, typing anything to the type_defs search bar will throw an exception:
```
Traceback (most recent call last):
  File "/home/korcan/PINCE_test/PINCE.py", line 4994, in highlight_text
    cursor.movePosition(QTextCursor.Start)
AttributeError: type object 'QTextCursor' has no attribute 'Start'
Traceback (most recent call last):
  File "/home/korcan/PINCE_test/PINCE.py", line 4994, in highlight_text
    cursor.movePosition(QTextCursor.Start)
AttributeError: type object 'QTextCursor' has no attribute 'Start'
```
- Clicking any cell in HexView throws an exception:
```
Traceback (most recent call last):
  File "/home/korcan/PINCE_test/PINCE.py", line 2789, in exec_hex_view_edit_dialog
    HexEditDialogForm(hex(selected_address)).exec()
  File "/home/korcan/PINCE_test/PINCE.py", line 4716, in __init__
    self.refresh_view()
  File "/home/korcan/PINCE_test/PINCE.py", line 4774, in refresh_view
    ascii_str = SysUtils.aob_to_str(aob_array, "utf-8")
  File "/home/korcan/PINCE_test/libpince/SysUtils.py", line 686, in aob_to_str
    byte=int(sByte,16)
TypeError: int() can't convert non-string with explicit base
```
- HexView does not render watchpoints, normally any visible cell within HexView gets painted with a red background if a watchpoint crosses the said cell
- HexView in this patch behaves way better than the original, really good job on this one but I've noticed that you have to pull StackTrace all the way to the right to view the contents of HexView fully. Maybe the design could be changed. However this is just an observation, not really a bug. I'm willing to accept it with its current state, it's just an idea for the future

**Comment by neoh4x0r** [comment]
> TypeError: setMinimumWidth(self, int): argument 1 has unexpected type 'float'
> AttributeError: type object 'Qt' has no attribute 'Window'
> AttributeError: type object 'Qt' has no attribute 'FramelessWindowHint'
> AttributeError: type object 'QTextCursor' has no attribute 'Start'
> TypeError: int() can't convert non-string with explicit base

**I just pushed some updates to address these issues.**

+ For setting the width: just cast the argument to an int (since the documentation says the argument is an int)
+ Updated use of more Qt enum values -- the enum name must be prefixed before the member (eg. Qt.Enum.Member).
+ Added a test in aob_to_str to treat any non-string value the same as ?? and replace it with a period.
    + Really need to determine what the data type (and its value) is when it's a non-string value -- my guess is that it is a numeric value (if this were the case, then call to int() could be skipped, since it would already be a numeric value -- but might need to be cast to an int for conversion to a two-character hex value).

**Comment by korcankaraokcu** [comment]
> Really need to determine what the data type (and its value) is when it's a non-string value

What do you mean by this? It's only used by HexView and AsciiView as I recall. So the only usage is hexdump. The original argument was a list of strings, which used as integers. I see that you've changed the design to have both strings and non-strings which I'm also okay with but generally speaking, I don't think that this function will process anything other than hex values submitted by the user. Please correct me if I misunderstood the question

About the remaining issues:
- Break and Trace Instructions and function search features still aren't working, they throw the same exception:
```
raceback (most recent call last):
  File "/home/korcan/PINCE_test/PINCE.py", line 3624, in tableWidget_Disassemble_context_menu_event
    actions[action]()
  File "/home/korcan/PINCE_test/PINCE.py", line 3657, in exec_trace_instructions_dialog
    trace_instructions_window = TraceInstructionsWindowForm(current_address, parent=self)
  File "/home/korcan/PINCE_test/PINCE.py", line 4509, in __init__
    self.wait_dialog = TraceInstructionsWaitWidgetForm(address, breakpoint, self)
  File "/home/korcan/PINCE_test/PINCE.py", line 4444, in __init__
    self.movie.setCacheMode(QMovie.CacheAll)
AttributeError: type object 'QMovie' has no attribute 'CacheAll'
```

The rest of the issues above are fixed, thank you for the work. However, I've noticed one issue with the hex edit dialog, despite clicking on valid utf-8 characters on the AsciiView, hex edit dialog always show `?`

**Comment by neoh4x0r** [comment]
> despite clicking on valid utf-8 characters on the AsciiView, hex edit dialog always show `?`

The reason for this is addressed in the next point.

> > Really need to determine what the data type (and its value) is when it's a non-string value
> 
> What do you mean by this? It's only used by HexView and AsciiView as I recall. So the only usage is hexdump. 
> The original argument was a list of strings, which used as integers. I see that you've changed the design to
> have both strings and non-strings which I'm also okay with but generally speaking, I don't think that this
> function will process anything other than hex values submitted by the user. Please correct me if I
> misunderstood the question


It seems that the problem was that list_of_bytes had two different types (str and list)

+ When displaying via HexView -- the type of list_of_bytes is 'str'
+ When displaying via HexView Edit dialog -- the type of list_of_bytes is 'list'

Moreover, to make the hex and ascii view look neater (by replacing non-printable chars with '.') it will
interfere with the Hex edit dialog -- the non-printable hex bytes will be replace with 2e if any edit was made.

If a cleaner look for the ascii text is wanted (in the memory view), then I think that the the editor dialog
should only allow editing the bytes (the ascii text should be read-only).

So, I have updated the **aob_to_str** to account for the two different types and have disabled the replacement
of the non-printable characters (for now).

> About the remaining issues:
> 
> * Break and Trace Instructions and function search features still aren't working, they throw the same exception:
> 
>> AttributeError: type object 'QMovie' has no attribute 'CacheAll'

Yeah, this was another enum value missing its enclosing type: QMovie.CacheMode.CacheAll (which has been fixed)

**Comment by korcankaraokcu** [comment]
> If a cleaner look for the ascii text is wanted (in the memory view), then I think that the the editor dialog
should only allow editing the bytes (the ascii text should be read-only)

The more I think about it the more it makes sense as well. Users can already add byte arrays to the address table if they want to edit in a more detailed way. Hex edit being used only for simple stuff makes sense, go for it. Btw, you can disable user input for the first QLineEdit via `HexEditDialog.ui` file, no need to include it within pince.py. You probably already know but just saying, UI files can be edited via `designer-qt6`. You might also need to install `qt6-base-dev` for the designer

About the issues, everything seems to be fixed except one thing, the breakpoint indicator:
> HexView does not render watchpoints, normally any visible cell within HexView gets painted with a red background if a watchpoint crosses the said cell

I've read the documentation a bit and found the culprit. Apparently the way it's handled in HexModel isn't working anymore. In the HexModel line 43, you can use `return QVariant(QColor("red"))` instead to make it work. I've learned this by looking at this page:
https://doc.qt.io/qt-6/qcolor.html
You are free to implement any solution of yours if this looks a bit ugly but I'm fine with anything really, as long as it works properly

**Comment by korcankaraokcu** [comment]
@neoh4x0r How is it going? I can fix the last 2 issues by myself if you want. A short reply on your availability is sufficient

**Comment by neoh4x0r** [comment]
> @neoh4x0r How is it going? I can fix the last 2 issues by myself if you want. A short reply on your availability is sufficient

Yeah I have been somewhat busy over the last month (and i still am), if you want to go ahead and fix them that works for me.

**Comment by korcankaraokcu** [comment]
Aight, I'll update the PR soon. Thanks for your contributions, I really appreciate it

**Comment by korcankaraokcu** [comment]
@N00byKing you can merge this PR, I'll make the changes afterwards. Apparently I need permission from you for direct commits to this branch. Since I can just edit afterwards, there's no need to complicate things

**Comment by N00byKing** [comment]
Alright, I've merged it

**Comment by korcankaraokcu** [comment]
@neoh4x0r I've fixed the breakpoint issue. Remembered that there was another PR about HexEditDialog, so I think I'll check it out first, will be updating about the situtation

**Comment by korcankaraokcu** [comment]
Forgot to update here about HexEditDialog. After disabling the ascii part locally, I've realized that I like the original functionality better in practice despite my previous thoughts. So yeah, decided to leave it as it was before. I think it'll be redundant eventually anyway if we ever implement cell repaint for the hex editor like CE does

@N00byKing Since the PR was merged, you can delete this fork if you like to. Thank you for the great efforts yet again. Further discussion will be held within the PINCE's issue tracker. Have a great day!

**Pull request merged**
